# ----------------------------------------------------------------------------------------------------------------------
# EXAMPLE: asi_camera_shoot
# ----------------------------------------------------------------------------------------------------------------------

add_executable(Example_asi_camera_shoot main.cpp)
target_link_libraries(Example_asi_camera_shoot PRIVATE DegorasASI)

# **********************************************************************************************************************
