# ----------------------------------------------------------------------------------------------------------------------
# EXAMPLE: asi_camera_frame_callback
# ----------------------------------------------------------------------------------------------------------------------

add_executable(Example_asi_camera_frame_callback main.cpp)
target_link_libraries(Example_asi_camera_frame_callback PRIVATE DegorasASI)

# **********************************************************************************************************************
