# ----------------------------------------------------------------------------------------------------------------------
# EXAMPLE: basic_camera_discovery
# ----------------------------------------------------------------------------------------------------------------------

add_executable(Example_basic_camera_discovery main.cpp)
target_link_libraries(Example_basic_camera_discovery PRIVATE DegorasASI)

# **********************************************************************************************************************
