# ----------------------------------------------------------------------------------------------------------------------
# EXAMPLE: asi_camera_capture
# ----------------------------------------------------------------------------------------------------------------------

add_executable(Example_asi_camera_capture main.cpp)
target_link_libraries(Example_asi_camera_capture PRIVATE DegorasASI)

# **********************************************************************************************************************
